[env:tbeam]
platform = espressif32
board = ttgo-t-beam
framework = arduino
monitor_speed = 115200
build_src_filter = +<openbot/>
test_ignore = *

[env:tbeam_keyboard]
extends = env:tbeam
build_src_filter = +<keyboard/>

[env:native]
platform = native
test_framework = unity
